### ISSUE TITLE
Does this work with letsencrypt-nosudo?

### ISSUE THREAD

**Issue by zenny** [artyom/leproxy#2]
Hi,

Just wondering whether leproxy works with https://github.com/diafygi/letsencrypt-nosudo or only works with the official certbot?

Cheers,
/z

**Comment by artyom** [comment]
You don't need to run leproxy as root, it only needs to be able to bind to ports :443 and :80, which can be done with linux capabilities:

    setcap cap_net_bind_service=+ep $(which leproxy)

On Debian/Ubuntu, `setcap` command can be found in `libcap2-bin` package.
